name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet build "LIS_Api.csproj" --configuration Release
      working-directory: ./LIS_Api
    - name: Test
      run: dotnet test "LIS_ApiTests.csproj" --configuration Release
      working-directory: ./LIS_ApiTests
